version: '3.8'

services:
  backend:
    container_name: transfert-devise-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2077:2077"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/transfert_devise?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - my-network
  #    restart: always

  db:
    image: mysql:latest
    container_name: db
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: transfert_devise
      MYSQL_USER: joel
      MYSQL_PASSWORD: joel
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - database-data:/var/lib/mysql
    networks:
      - my-network
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "9999:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    networks:
      - my-network

networks:
  my-network:

volumes:
  database-data:

